##############################################################################
#
# Assignment and Constraints Quartus TCL script for design H:\ISEProject\EDIF\ISEProject.edf
#
# Generated by DK Design Suite (Version 5.2.6266.11181)
# Timestamp 2011 5 27 12 20 11
#
##############################################################################


# Set family and part
set_global_assignment -name FAMILY "CYCLONE II"
set_global_assignment -name DEVICE "ep2c35f672c6"

# Set compilation options
set_global_assignment -name ALLOW_POWER_UP_DONT_CARE Off
set_global_assignment -name AUTO_PACKED_REGISTERS Normal


############################### IO assignments ###############################

set_location_assignment PIN_V13 -to PIN_V13
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_V13
set_location_assignment PIN_V14 -to PIN_V14
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_V14
set_location_assignment PIN_AE11 -to PIN_AE11
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AE11
set_location_assignment PIN_AD11 -to PIN_AD11
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AD11
set_location_assignment PIN_AC12 -to PIN_AC12
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AC12
set_location_assignment PIN_AB12 -to PIN_AB12
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AB12
set_location_assignment PIN_AF10 -to PIN_AF10
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AF10
set_location_assignment PIN_AB24 -to PIN_AB24
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AB24
set_location_assignment PIN_AA23 -to PIN_AA23
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AA23
set_location_assignment PIN_AA24 -to PIN_AA24
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AA24
set_location_assignment PIN_Y22 -to PIN_Y22
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_Y22
set_location_assignment PIN_W21 -to PIN_W21
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_W21
set_location_assignment PIN_V21 -to PIN_V21
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_V21
set_location_assignment PIN_V20 -to PIN_V20
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_V20
set_location_assignment PIN_Y24 -to PIN_Y24
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_Y24
set_location_assignment PIN_AB25 -to PIN_AB25
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AB25
set_location_assignment PIN_AB26 -to PIN_AB26
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AB26
set_location_assignment PIN_AC26 -to PIN_AC26
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AC26
set_location_assignment PIN_AC25 -to PIN_AC25
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AC25
set_location_assignment PIN_V22 -to PIN_V22
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_V22
set_location_assignment PIN_AB23 -to PIN_AB23
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AB23
set_location_assignment PIN_W24 -to PIN_W24
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_W24
set_location_assignment PIN_U22 -to PIN_U22
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_U22
set_location_assignment PIN_Y25 -to PIN_Y25
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_Y25
set_location_assignment PIN_Y26 -to PIN_Y26
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_Y26
set_location_assignment PIN_AA26 -to PIN_AA26
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AA26
set_location_assignment PIN_AA25 -to PIN_AA25
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AA25
set_location_assignment PIN_Y23 -to PIN_Y23
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_Y23
set_location_assignment PIN_T3 -to PIN_T3
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_T3
set_location_assignment PIN_R6 -to PIN_R6
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_R6
set_location_assignment PIN_R7 -to PIN_R7
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_R7
set_location_assignment PIN_T4 -to PIN_T4
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_T4
set_location_assignment PIN_U2 -to PIN_U2
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_U2
set_location_assignment PIN_U1 -to PIN_U1
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_U1
set_location_assignment PIN_U9 -to PIN_U9
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_U9
set_location_assignment PIN_R3 -to PIN_R3
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_R3
set_location_assignment PIN_R4 -to PIN_R4
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_R4
set_location_assignment PIN_R5 -to PIN_R5
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_R5
set_location_assignment PIN_T9 -to PIN_T9
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_T9
set_location_assignment PIN_P7 -to PIN_P7
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_P7
set_location_assignment PIN_P6 -to PIN_P6
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_P6
set_location_assignment PIN_T2 -to PIN_T2
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_T2
set_location_assignment PIN_W26 -to PIN_W26
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_W26
set_location_assignment PIN_P23 -to PIN_P23
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_P23
set_location_assignment PIN_N23 -to PIN_N23
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_N23
set_location_assignment PIN_D13 -to PIN_D13
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_D13
set_location_assignment PIN_G26 -to PIN_G26
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_G26
set_location_assignment PIN_C24 -to PIN_C24
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_C24
set_location_assignment PIN_D26 -to PIN_D26
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_D26
set_location_assignment PIN_N2 -to PIN_N2
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_N2
set_location_assignment PIN_E10 -to PIN_E10
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_E10
set_location_assignment PIN_F11 -to PIN_F11
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_F11
set_location_assignment PIN_H12 -to PIN_H12
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_H12
set_location_assignment PIN_H11 -to PIN_H11
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_H11
set_location_assignment PIN_A8 -to PIN_A8
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_A8
set_location_assignment PIN_C9 -to PIN_C9
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_C9
set_location_assignment PIN_D9 -to PIN_D9
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_D9
set_location_assignment PIN_G10 -to PIN_G10
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_G10
set_location_assignment PIN_F10 -to PIN_F10
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_F10
set_location_assignment PIN_C8 -to PIN_C8
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_C8
set_location_assignment PIN_D12 -to PIN_D12
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_D12
set_location_assignment PIN_E12 -to PIN_E12
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_E12
set_location_assignment PIN_D11 -to PIN_D11
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_D11
set_location_assignment PIN_G11 -to PIN_G11
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_G11
set_location_assignment PIN_A10 -to PIN_A10
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_A10
set_location_assignment PIN_B10 -to PIN_B10
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_B10
set_location_assignment PIN_D10 -to PIN_D10
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_D10
set_location_assignment PIN_C10 -to PIN_C10
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_C10
set_location_assignment PIN_A9 -to PIN_A9
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_A9
set_location_assignment PIN_B9 -to PIN_B9
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_B9
set_location_assignment PIN_B12 -to PIN_B12
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_B12
set_location_assignment PIN_C12 -to PIN_C12
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_C12
set_location_assignment PIN_B11 -to PIN_B11
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_B11
set_location_assignment PIN_C11 -to PIN_C11
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_C11
set_location_assignment PIN_J11 -to PIN_J11
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_J11
set_location_assignment PIN_J10 -to PIN_J10
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_J10
set_location_assignment PIN_G12 -to PIN_G12
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_G12
set_location_assignment PIN_F12 -to PIN_F12
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_F12
set_location_assignment PIN_J14 -to PIN_J14
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_J14
set_location_assignment PIN_J13 -to PIN_J13
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_J13
set_location_assignment PIN_A7 -to PIN_A7
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_A7
set_location_assignment PIN_D8 -to PIN_D8
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_D8
set_location_assignment PIN_D6 -to PIN_D6
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_D6
set_location_assignment PIN_B8 -to PIN_B8
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_B8
set_location_assignment PIN_AD19 -to PIN_AD19
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AD19
set_location_assignment PIN_AC19 -to PIN_AC19
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AC19
set_location_assignment PIN_AF20 -to PIN_AF20
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AF20
set_location_assignment PIN_AE20 -to PIN_AE20
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AE20
set_location_assignment PIN_AB20 -to PIN_AB20
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AB20
set_location_assignment PIN_AC20 -to PIN_AC20
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AC20
set_location_assignment PIN_AF21 -to PIN_AF21
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AF21
set_location_assignment PIN_AE21 -to PIN_AE21
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AE21
set_location_assignment PIN_Y14 -to PIN_Y14
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_Y14
set_location_assignment PIN_Y15 -to PIN_Y15
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_Y15
set_location_assignment PIN_AA15 -to PIN_AA15
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AA15
set_location_assignment PIN_AB15 -to PIN_AB15
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AB15
set_location_assignment PIN_AC15 -to PIN_AC15
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AC15
set_location_assignment PIN_AE16 -to PIN_AE16
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AE16
set_location_assignment PIN_AD16 -to PIN_AD16
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AD16
set_location_assignment PIN_AC16 -to PIN_AC16
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AC16
set_location_assignment PIN_W15 -to PIN_W15
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_W15
set_location_assignment PIN_W16 -to PIN_W16
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_W16
set_location_assignment PIN_AF17 -to PIN_AF17
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AF17
set_location_assignment PIN_AE17 -to PIN_AE17
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AE17
set_location_assignment PIN_AC17 -to PIN_AC17
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AC17
set_location_assignment PIN_AD17 -to PIN_AD17
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AD17
set_location_assignment PIN_AA16 -to PIN_AA16
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AA16
set_location_assignment PIN_Y16 -to PIN_Y16
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_Y16
set_location_assignment PIN_AF18 -to PIN_AF18
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AF18
set_location_assignment PIN_AE18 -to PIN_AE18
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AE18
set_location_assignment PIN_AF19 -to PIN_AF19
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AF19
set_location_assignment PIN_AE19 -to PIN_AE19
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AE19
set_location_assignment PIN_AB18 -to PIN_AB18
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AB18
set_location_assignment PIN_AC18 -to PIN_AC18
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AC18
set_location_assignment PIN_V17 -to PIN_V17
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_V17
set_location_assignment PIN_W17 -to PIN_W17
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_W17
set_location_assignment PIN_AA18 -to PIN_AA18
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AA18
set_location_assignment PIN_AA17 -to PIN_AA17
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AA17
set_location_assignment PIN_AC10 -to PIN_AC10
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AC10
set_location_assignment PIN_AC9 -to PIN_AC9
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AC9
set_location_assignment PIN_W12 -to PIN_W12
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_W12
set_location_assignment PIN_W11 -to PIN_W11
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_W11
set_location_assignment PIN_AF8 -to PIN_AF8
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AF8
set_location_assignment PIN_AE8 -to PIN_AE8
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AE8
set_location_assignment PIN_AF7 -to PIN_AF7
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AF7
set_location_assignment PIN_AE7 -to PIN_AE7
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AE7
set_location_assignment PIN_Y11 -to PIN_Y11
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_Y11
set_location_assignment PIN_AA11 -to PIN_AA11
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AA11
set_location_assignment PIN_AB10 -to PIN_AB10
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AB10
set_location_assignment PIN_AA10 -to PIN_AA10
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AA10
set_location_assignment PIN_AA9 -to PIN_AA9
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AA9
set_location_assignment PIN_AF6 -to PIN_AF6
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AF6
set_location_assignment PIN_AE6 -to PIN_AE6
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AE6
set_location_assignment PIN_AD8 -to PIN_AD8
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AD8
set_location_assignment PIN_AC8 -to PIN_AC8
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AC8
set_location_assignment PIN_AB8 -to PIN_AB8
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AB8
set_location_assignment PIN_Y10 -to PIN_Y10
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_Y10
set_location_assignment PIN_W10 -to PIN_W10
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_W10
set_location_assignment PIN_W8 -to PIN_W8
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_W8
set_location_assignment PIN_AC7 -to PIN_AC7
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AC7
set_location_assignment PIN_V9 -to PIN_V9
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_V9
set_location_assignment PIN_V10 -to PIN_V10
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_V10
set_location_assignment PIN_AD7 -to PIN_AD7
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AD7
set_location_assignment PIN_AD6 -to PIN_AD6
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AD6
set_location_assignment PIN_AF5 -to PIN_AF5
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AF5
set_location_assignment PIN_AE5 -to PIN_AE5
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AE5
set_location_assignment PIN_AD5 -to PIN_AD5
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AD5
set_location_assignment PIN_AD4 -to PIN_AD4
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AD4
set_location_assignment PIN_AC6 -to PIN_AC6
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AC6
set_location_assignment PIN_AC5 -to PIN_AC5
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AC5
set_location_assignment PIN_AF4 -to PIN_AF4
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AF4
set_location_assignment PIN_AE4 -to PIN_AE4
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AE4
set_location_assignment PIN_AC11 -to PIN_AC11
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AC11
set_location_assignment PIN_AE10 -to PIN_AE10
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AE10
set_location_assignment PIN_AD10 -to PIN_AD10
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AD10
set_location_assignment PIN_AE9 -to PIN_AE9
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AE9
set_location_assignment PIN_AF9 -to PIN_AF9
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_AF9


############################# Timing requirements ############################

timegroup CelSynTimeGroup2 -add_member B726_ISEProject_hcc_1214_DTYPE0IR
timegroup CelSynTimeGroup3 -add_member B727_ISEProject_hcc_1214_DTYPE0IR
timegroup CelSynTimeGroup3 -add_member B728_ISEProject_hcc_1214_DTYPE0IR
timegroup CelSynTimeGroup3 -add_member B729_ISEProject_hcc_1214_DTYPE0IR
timegroup CelSynTimeGroup3 -add_member B730_ISEProject_hcc_1214_DTYPE0IR
timegroup CelSynTimeGroup3 -add_member B731_ISEProject_hcc_1214_DTYPE0IR
timegroup CelSynTimeGroup3 -add_member B732_ISEProject_hcc_1214_DTYPE0IR
timegroup CelSynTimeGroup3 -add_member B733_ISEProject_hcc_1214_DTYPE0IR
timegroup CelSynTimeGroup3 -add_member B734_ISEProject_hcc_1214_DTYPE0IR
timegroup CelSynTimeGroup3 -add_member B735_ISEProject_hcc_1214_DTYPE0IR
timegroup CelSynTimeGroup3 -add_member B736_ISEProject_hcc_1214_DTYPE0IR
set_instance_assignment -name X_ON_VIOLATION_OPTION OFF -to B727_ISEProject_hcc_1214_DTYPE0IR
set_instance_assignment -name X_ON_VIOLATION_OPTION OFF -to B728_ISEProject_hcc_1214_DTYPE0IR
set_instance_assignment -name X_ON_VIOLATION_OPTION OFF -to B729_ISEProject_hcc_1214_DTYPE0IR
set_instance_assignment -name X_ON_VIOLATION_OPTION OFF -to B730_ISEProject_hcc_1214_DTYPE0IR
set_instance_assignment -name X_ON_VIOLATION_OPTION OFF -to B731_ISEProject_hcc_1214_DTYPE0IR
set_instance_assignment -name X_ON_VIOLATION_OPTION OFF -to B732_ISEProject_hcc_1214_DTYPE0IR
set_instance_assignment -name X_ON_VIOLATION_OPTION OFF -to B733_ISEProject_hcc_1214_DTYPE0IR
set_instance_assignment -name X_ON_VIOLATION_OPTION OFF -to B734_ISEProject_hcc_1214_DTYPE0IR
set_instance_assignment -name X_ON_VIOLATION_OPTION OFF -to B735_ISEProject_hcc_1214_DTYPE0IR
set_instance_assignment -name X_ON_VIOLATION_OPTION OFF -to B736_ISEProject_hcc_1214_DTYPE0IR
set_instance_assignment -name MAX_DELAY -from CelSynTimeGroup3 -to CelSynTimeGroup2 2.000ns
set_instance_assignment -name MAX_DELAY -from CelSynTimeGroup3 -to CelSynTimeGroup3 2.000ns
